# Generated by Django 4.0.4 on 2022-05-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_lastname', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(unique=True)),
                ('contact_email', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('contact_birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessions_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_sesion_id', models.CharField(blank=True, max_length=400, null=True, unique=True)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(max_length=20, unique=True)),
                ('user_firstname', models.CharField(max_length=20)),
                ('user_lastname', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Sessions',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
